# Generated by Django 5.1.6 on 2025-02-28 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_account',
            fields=[
                ('account_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('branch_code', models.CharField(max_length=10)),
                ('account_type', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_photo', models.FileField(upload_to='static/Admin/lib/cus-photo')),
                ('date_of_birth', models.DateField()),
                ('c_residence', models.CharField(max_length=100)),
                ('c_phone_number', models.BigIntegerField(unique=True)),
                ('c_email', models.EmailField(max_length=254)),
                ('aadhar_number', models.BigIntegerField(unique=True)),
                ('min_balance', models.BigIntegerField()),
                ('main_balance', models.BigIntegerField()),
                ('opening_date', models.DateField()),
                ('co_name', models.CharField(max_length=50, null=True)),
                ('co_relation', models.CharField(max_length=30, null=True)),
                ('co_residence', models.CharField(max_length=100, null=True)),
                ('co_idproof', models.FileField(null=True, upload_to='static/Admin/lib/co-id-proof')),
                ('account_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_admin',
            fields=[
                ('admin_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('admin_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('ad_email', models.EmailField(max_length=254, unique=True)),
                ('ad_phone', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'tb_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_customer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('c_name', models.CharField(max_length=50)),
                ('c_password', models.CharField(max_length=30)),
                ('security_pin', models.IntegerField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.tb_account')),
            ],
            options={
                'db_table': 'tb_customer',
                'managed': True,
            },
        ),
    ]
